{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: academico-secrets
  labels:
    {{- include "academico.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.databaseUser | quote }}
  DB_PASSWORD: {{ .Values.secret.databasePassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
{{- end }}
